server:
  port: @order.service.port@
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_order?useSSL=false
    username: root
    password: 15947035212
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: HZ
        namespace: @namespace@
  application:
    name: order-service
  redis:
    host: localhost
    port: 6379
    database: 1
snowflake:
  application-name: order-service
  datacenter-id: 1

