spring:
  redis:
    host: localhost
    port: 6379
    database: 1
  shardingsphere:
    datasource:
      # 数据源（不能使用下划线分隔）
      names: ds-user,ds-order,ds-quartz,ds-pay,ds-product
      ds-user:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/db_user?useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 15947035212
      ds-order:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/db_order?useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 15947035212
      ds-quartz:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/db_quartz?useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 15947035212
      ds-pay:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/db_pay?useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 15947035212
      ds-product:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/db_product?useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 15947035212

    sharding:
      tables:
        #表 （逻辑表名，可以使用下划线分隔，与@tablename中值相同）
        #db-user
        user:
          actual-data-nodes: ds-user.user_$->{0..9}
          table-strategy:
            inline:
              sharding-column: user_id
              algorithm-expression: user_$->{user_id % 10}
        dict_role:
          actual-data-nodes: ds-user.dict_role
        permission:
          actual-data-nodes: ds-user.permission_$->{0..9}
          table-strategy:
            inline:
              sharding-column: user_id
              algorithm-expression: permission_$->{user_id % 10}
        #db-pay
        payment_info:
          actual-data-nodes: ds-pay.payment_info_$->{0..9}
          table-strategy:
            inline:
              sharding-column: payment_id
              algorithm-expression: payment_info_$->{payment_id % 10}
        refund_info:
          actual-data-nodes: ds-pay.refund_info_$->{0..9}
          table-strategy:
            inline:
              sharding-column: refund_id
              algorithm-expression: refund_info_$->{refund_id % 10}
        #db-order
        order_master:
          actual-data-nodes: ds-order.order_master_$->{0..9}
          table-strategy:
            inline:
              sharding-column: order_id
              algorithm-expression: order_master_$->{order_id % 10}
        order_item:
          actual-data-nodes: ds-order.order_item_$->{0..9}
          table-strategy:
            inline:
              sharding-column: item_id
              algorithm-expression: order_item_$->{item_id % 10}
        order_operation:
          actual-data-nodes: ds-order.order_operation_log_$->{0..9}
          table-strategy:
            inline:
              sharding-column: log_id
              algorithm-expression: order_operation_$->{log_id % 10}
        #db-product
        product_brand:
          actual-data-nodes: ds-product.product_brand
        product_category:
          actual-data-nodes: ds-product.product_category
        product_spu:
          actual-data-nodes: ds-product.product_spu
        product_sku:
          actual-data-nodes: ds-product.product_sku_$->{0..9}
          table-strategy:
            inline:
              sharding-column: sku_id
              algorithm-expression: product_sku_$->{sku_id % 10}
        product_image:
          actual-data-nodes: ds-product.product_image_$->{0..9}
          table-strategy:
            inline:
              sharding-column: image_id
              algorithm-expression: product_image_$->{image_id % 10}
        product_attribute:
          actual-data-nodes: ds-product.product_attribute_$->{0..9}
          table-strategy:
            inline:
              sharding-column: attr_id
              algorithm-expression: product_attribute_$->{attr_id % 10}
        inventory_log:
          actual-data-nodes: ds-product.inventory_log_$->{0..9}
          table-strategy:
            inline:
              sharding-column: log_id
              algorithm-expression: inventory_log_$->{log_id % 10}
        #db-quartz
        task:
          actual-data-nodes: ds-quartz.task
        task_log:
          actual-data-nodes: ds-quartz.task_log


    props:
      sql:
        show: false
snowflake:
  datacenter-id: 1
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.bit.pojo.po
  configuration:
    map-underscore-to-camel-case: true

#security
password-encoder:
  strength: 10
jwt:
  secret: wlf18086270070
  accessTokenExpiration: 86400 #单位秒  1天
  refreshTokenExpiration: 2592000 #单位秒 1月
  internalTokenExpiration: 5 #单位秒 5秒
