spring:
  redis:
    host: localhost
    port: 6379
    database: 1
  shardingsphere:
    props:
      sql:
        show: false
snowflake:
  datacenter-id: 1
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.bit.pojo.po
  configuration:
    map-underscore-to-camel-case: true

#security
password-encoder:
  strength: 10
jwt:
  secret: wlf18086270070
  accessTokenExpiration: 86400 #单位秒  1天
  refreshTokenExpiration: 2592000 #单位秒 1月
  internalTokenExpiration: 5 #单位秒 5秒
