server:
  port: @quartz.port@
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_quartz?useSSL=false
    username: root
    password: 15947035212
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: quartz
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: cn.bit.pro1_1.core.mapper